name: Check

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          node-version: 24

      - name: Install dependencies
        run: vp install

      - name: Check
        run: vp check

      - name: Test
        run: vp test
